// Each #kernel tells which function to compile; you can have many kernels

//WORLEY NOISE
RWTexture3D<float4> _Noise3D;
int _TargetChannel;
uint _WorleyTextureSize; //Texture resolution is _WorleyTextureSize^3
int _WorleyBaseFreq;//Total grid cells
int _WorleyNumOctaves; //Number of fBm layers
//persistance? //weight decrease per layer (typically 0.5)
//lacunarity? //power by which frequency is scaled between octaves (typically 2)

// Hash by David_Hoskins
#define UI0 1597334673u
#define UI1 3812015801u
#define UI2 uint2(UI0, UI1)
#define UI3 uint3(UI0, UI1, 2798796415u)
#define UIF (1.0 / float(0xffffffffU))

float3 hash33(float3 p)
{
    uint3 q = uint3((int3) p) * UI3;
    q = (q.x ^ q.y ^ q.z) * UI3;
    
    return -1.0 + 2.0 * float3(q) * UIF;
}

float3 mod(float3 x, float y)
{
    return x - y * floor(x / y);
}

float generateWorley(float3 pos, int freq)
{
    int3 cell = floor(pos);
    float3 pointInCell = frac(pos);
    float minSqrDist = 1;
    
    //loops through all 27 neighboring cells
    for (int x = -1; x < 2; x++){
        for (int y = -1; y < 2; y++){
            for (int z = -1; z < 2; z++){
                int3 neighborCell = cell + int3(x, y, z); //offset; one of 27 neighboring cells surrounding the point
                float3 pnt = hash33(mod(neighborCell, freq)) * .5 + .5;
                pnt += int3(x, y, z); //pnt represents nearest "dot"
                //find distance between pointInCell & pnt
                float3 diff = pointInCell - pnt;
                minSqrDist = min(minSqrDist, dot(diff, diff));
            }
        }
    }
    
    return saturate(1 - sqrt(minSqrDist)); //****** USE WITHOUT SQRT? *******
}

#pragma kernel worleyNoise3D

[numthreads(8, 8, 8)]
void worleyNoise3D(uint3 id : SV_DispatchThreadID)
{
    //Bounds check
    if (id.x >= _WorleyTextureSize || id.y >= _WorleyTextureSize || id.z >= _WorleyTextureSize)
        return;
    
    float4 current = _Noise3D[id];
    float3 pos = (float3) id / (float) _WorleyTextureSize;
    
    float _WorleyPersistance = 0.5;
    float _WorleyLacunarity = 2;

    float localFreq = _WorleyBaseFreq;
    float amp = 1;
    float noise = 0;
    float totalAmp = 0;
    for (int i = 0; i < _WorleyNumOctaves; i++)
    {
        noise += amp * generateWorley(pos * localFreq, localFreq);
        totalAmp += amp;
        localFreq *= _WorleyLacunarity;
        amp *= _WorleyPersistance;
    }
    noise /= totalAmp;
    float4 result = _Noise3D[id];
    if (_TargetChannel == 0) result.r = noise;
    else if (_TargetChannel == 1) result.g = noise;
    else if (_TargetChannel == 2) result.b = noise;
    else result.a = noise;

    _Noise3D[id] = result;
}

//PERLIN NOISE
uint _PerlinTextureSize; //Texture resolution is _PerlinTextureSize^3
int _PerlinBaseFreq; //Total grid cells
int _PerlinNumOctaves; //Number of fBm layers
//persistance? //weight decrease per layer (typically 0.5)
//lacunarity? //power by which frequency is scaled between octaves (typically 2)

float determines(float u)
{
    return 6 * (u * u * u * u * u) - 15 * (u * u * u * u) + 10 * (u * u * u);
}

float3 determinet(float3 uvw)
{
    return float3(determines(uvw.x), determines(uvw.y), determines(uvw.z));
}

float remap(float value, float minOld, float maxOld, float minNew, float maxNew)
{
    float ratio = (maxNew - minNew) / (maxOld - minOld);
    return minNew + (value - minOld) * ratio;
}

float generatePerlin(float3 pos, float freq)//function generates one octave of perlin noise
{
    float3 cell = floor(pos);
    float3 pointInCell = frac(pos);
    float perlin = 0;
    float3 t = determinet(pointInCell);//interpolant
    float dots[8];//dot products between pointInCell and gradients
    for (int z = 0; z < 2; z++){
        for (int y = 0; y < 2; y++){
            for (int x = 0; x < 2; x++){
                float3 neighborCell = cell + int3(x, y, z); //offset; one of 8 corners of the cube surrounding the point
                
                float3 gradient = hash33(mod(neighborCell, freq));
                float dotProd = dot(gradient, pointInCell - float3(x, y, z));
                dots[x + y * 2 + z * 4] = dotProd;
            }
        }
    }
    
    //lerps between x corners, then y corners, then finally z
    float lerpX00 = lerp(dots[0], dots[1], t.x);
    float lerpX10 = lerp(dots[2], dots[3], t.x);
    float lerpX01 = lerp(dots[4], dots[5], t.x);
    float lerpX11 = lerp(dots[6], dots[7], t.x);

    float lerpY0 = lerp(lerpX00, lerpX10, t.y);
    float lerpY1 = lerp(lerpX01, lerpX11, t.y);

    perlin = lerp(lerpY0, lerpY1, t.z);
    return perlin;
}

float gradientNoise(float3 x, float freq)
{
    // grid
    //return hash33(x).x;
    float3 p = floor(x);
    float3 w = frac(x);
    
    // quintic interpolant
    float3 u = w * w * w * (w * (w * 6. - 15.) + 10.);

    
    // gradients
    float3 ga = hash33(mod(p + float3(0., 0., 0.), freq));
    float3 gb = hash33(mod(p + float3(1., 0., 0.), freq));
    float3 gc = hash33(mod(p + float3(0., 1., 0.), freq));
    float3 gd = hash33(mod(p + float3(1., 1., 0.), freq));
    float3 ge = hash33(mod(p + float3(0., 0., 1.), freq));
    float3 gf = hash33(mod(p + float3(1., 0., 1.), freq));
    float3 gg = hash33(mod(p + float3(0., 1., 1.), freq));
    float3 gh = hash33(mod(p + float3(1., 1., 1.), freq));
    
    // projections
    float va = dot(ga, w - float3(0., 0., 0.));
    float vb = dot(gb, w - float3(1., 0., 0.));
    float vc = dot(gc, w - float3(0., 1., 0.));
    float vd = dot(gd, w - float3(1., 1., 0.));
    float ve = dot(ge, w - float3(0., 0., 1.));
    float vf = dot(gf, w - float3(1., 0., 1.));
    float vg = dot(gg, w - float3(0., 1., 1.));
    float vh = dot(gh, w - float3(1., 1., 1.));
	
    // interpolation
    return va +
           u.x * (vb - va) +
           u.y * (vc - va) +
           u.z * (ve - va) +
           u.x * u.y * (va - vb - vc + vd) +
           u.y * u.z * (va - vc - ve + vg) +
           u.z * u.x * (va - vb - ve + vf) +
           u.x * u.y * u.z * (-va + vb + vc - vd + ve - vf - vg + vh);
}

#pragma kernel perlinNoise3D

[numthreads(8, 8, 8)]
void perlinNoise3D(uint3 id : SV_DispatchThreadID)
{
    if (id.x >= _PerlinTextureSize || id.y >= _PerlinTextureSize || id.z >= _PerlinTextureSize)
        return;
    
    float4 current = _Noise3D[id];
    float3 pos = ((float3) id + 0.5) / (float) _PerlinTextureSize;
    
    //these variables could be added to the buffer for more control
    float _PerlinPersistance = exp2(-0.85);
    float _Cloudiness = 0.5;
    float _PerlinLacunarity = 2;
    
    float localFreq = _PerlinBaseFreq;
    float amp = 1;
    float noise = 0;
    float totalAmp = 0;
    for (int i = 0; i < _PerlinNumOctaves; i++)
    {
        noise += amp * gradientNoise(pos * localFreq, localFreq);
        localFreq *= _PerlinLacunarity;
        amp *= _PerlinPersistance;
    }
    noise = noise * 0.5 + 0.5;
    noise = abs((noise * 2) - 1);
    float worley = current.r;
    float perlinWorley = remap(noise, 0, 1, worley, 1);
    //perlinWorley = worley;
    _Noise3D[id] = float4(perlinWorley, current.g, current.b, current.a);
    //_Noise3D[id] = float4(current.r, current.g, current.b, current.a);
    //_Noise3D[id] = float4(current.r, current.r, current.r, current.r);
    //_Noise3D[id] = float4(perlinWorley, perlinWorley, perlinWorley, perlinWorley);
}

RWStructuredBuffer<float3> _vertices;

#pragma kernel simplexNoise

[numthreads(64, 1, 1)]
void simplexNoise(uint3 id : SV_DispatchThreadID)
{
    float3 vertex = _vertices[id.x];
    
    float perlin = generatePerlin(vertex, 4);
    
    float final = perlin * 0.5 + 0.5;
    
    _vertices[id.x] *= 1 + final;
}
